mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^polls/', include('polls.urls')),
]

polls/urls.py
from django.conf.urls import url
from wkhtmltopdf.views import PDFTemplateView

from . import views

app_name = 'polls'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^sondages$', views.IndexSondageView.as_view(), name='indexSondage'),
	url(r'^questionnaires$', views.IndexQuestionnaireView.as_view(), name='indexQuestionnaire'),
	
	url(r'^sondages/(?P<pk>[0-9]+)/$', views.DetailSondageView.as_view(), name='detail'),
	url(r'^sondages/(?P<pk>[0-9]+)/results/$', views.ResultsSondageView.as_view(), name='results'),
	url(r'^sondages/(?P<question_id>[0-9]+)/vote/$', views.voteSondage, name='vote'),
	
	url(r'^questionnaires/(?P<pk>[0-9]+)/$', views.DetailQuestionnaireView.as_view(), name='detailQuestionnaire'),
	url(r'^questionnaires/(?P<pk>[0-9]+)/results/$', views.ResultsQuestionnaireView.as_view(), name='resultsQuestionnaire'),
	url(r'^questionnaires/(?P<questionnaire_id>[0-9]+)/reponse/$', views.reponseQuestionnaire, name='reponseQuestionnaire'),	
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

###############
### SONDAGE ###
###############

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('Date de publication')
	def __str__(self):
		return self.question_text
	# end def
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
	# end def

	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Publié récemment?'
# end class

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text
	# end def
# end class

class Reponse(models.Model):
	nom = models.CharField(max_length=50, default="Anonyme")
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
	def __str__(self):
		return self.nom+" - "+self.question.question_text+" - "+self.choice.choice_text
	# end def
# end class


#####################
### QUESTIONNAIRE ###
#####################

class Questionnaire(models.Model):
	label = models.CharField(max_length=100)
	pub_date = models.DateTimeField('Date de publication')
	def __str__(self):
		return self.label
	# end def
# end class

class QuestionQuestionnaire(models.Model):
	question = models.CharField(max_length=200)
	questionnaire = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)
	def __str__(self):
		return self.question
	# end def
# end class

class ReponseQuestionnaires(models.Model):
	nom = models.CharField(max_length=50, default="Anonyme")
	questionnaire = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)
	date = models.DateTimeField('Date de reponse')
	def __str__(self):
		return self.nom+" - "+self.questionnaire.label
	# end def
# end class

class ReponseQuestionQuestionnaire(models.Model):
	question = models.CharField(max_length=200)
	reponse = models.CharField(max_length=200)
	reponse_questionnaire = models.ForeignKey(ReponseQuestionnaires, on_delete=models.CASCADE)
	def __str__(self):
		return self.reponse_questionnaire.nom+" - "+self.reponse_questionnaire.questionnaire.label+" - "+self.question
	# end def
# end class

polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question, Reponse
from .models import Questionnaire, QuestionQuestionnaire, ReponseQuestionnaires, ReponseQuestionQuestionnaire

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	queryset = Question.objects.all()
	
	def get_context_data(self, *args, **kwargs):
		context = super(IndexView, self).get_context_data(*args, **kwargs)
		context['latest_questionnaire_list'] = Questionnaire.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:3]
		context['latest_sondage_list'] = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:3]
		return context
	# end def 
# end class

class IndexSondageView(generic.ListView):
	template_name = 'polls/indexSondage.html'
	context_object_name = 'sondages'
	def get_queryset(self):
		#Retourne les 5 dernières questions publiées
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
	# end def
# end class

class IndexQuestionnaireView(generic.ListView):
	template_name = 'polls/indexQuestionnaire.html'
	context_object_name = 'questionnaires'
	def get_queryset(self):
		#Retourne les 5 dernières questions publiées
		return Questionnaire.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
	# end def
# end class


#############
## SONDAGE ##
#############

class DetailSondageView(generic.DetailView):
	model = Question
	template_name = 'polls/detailSondage.html'
	def get_queryset(self):
		#Exclus toutes les questions qui n'ont pas encore été publiées
		return Question.objects.filter(pub_date__lte=timezone.now())
	# end def
# end class

class ResultsSondageView(generic.DetailView):
	model = Question
	template_name = 'polls/resultsSondage.html'
# end class

def voteSondage(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		#Redirection vers la question avec le message d'erreur.
		return render(request, 'polls/detailSondage.html', {
			'question': question,
			'error_message': "Vous n'avez pas séléctionné de choix.",
		})
	else:
		#Enregistre le vote de la personne dans le choix
		selected_choice.votes += 1
		selected_choice.save()

		#Enregistre la reponse de la personne
		reponse = Reponse()
		nom = request.POST['nom']
		if nom != '' :
			reponse.nom = nom
		reponse.question = question
		reponse.choice = selected_choice
		reponse.save()

		#Redirection vers la page des résultats
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
	# end try
# end def

###################
## QUESTIONNAIRE ##
###################

class DetailQuestionnaireView(generic.DetailView):
	model = Questionnaire
	template_name = 'polls/detailQuestionnaire.html'
	def get_queryset(self):
		#Exclus tous les questionnaires qui n'ont pas encore été publiés
		return Questionnaire.objects.filter(pub_date__lte=timezone.now())
	# end def
# end class

class ResultsQuestionnaireView(generic.DetailView):
	model = Questionnaire
	template_name = 'polls/resultsQuestionnaire.html'
# end class

def reponseQuestionnaire(request, questionnaire_id):
	# Récupération du questionnaire
	questionnaire = get_object_or_404(Questionnaire, pk=questionnaire_id)	
	
	# Création de la reponse au questionnaire
	reponseQuest = ReponseQuestionnaires()
	nom = request.POST['nom']
	if nom != '' :
		reponseQuest.nom = nom
	else :
		reponseQuest.nom = "Anonyme"
	# end if
	reponseQuest.date = timezone.now()
	reponseQuest.questionnaire = questionnaire
	reponseQuest.save()
	
	# Parcours de toutes les questions du formulaire pour récupérer les réponses
	for question in questionnaire.questionquestionnaire_set.all():
		reponse = request.POST.get("reponse"+str(question.id),False)
		if (reponse != False):			
			reponseQuestQuest = ReponseQuestionQuestionnaire()
			reponseQuestQuest.question = question
			reponseQuestQuest.reponse = reponse
			reponseQuestQuest.reponse_questionnaire = reponseQuest
			reponseQuestQuest.save()
		# end if
	# end for
	
	#Redirection vers la page des résultats
	return HttpResponseRedirect(reverse('polls:resultsQuestionnaire', args=(questionnaire.id,)))
# end def

###################
## GENERTION PDF ##
###################
    

polls/templates/polls/detailSondage.html
{% extends "polls/layout.html" %}

{% block menuSondage %}
	class="active"
{% endblock menuSondage %}

{% block page %}
<div class="container">
	<div class="row">
		<h1>{{ question.question_text }}</h1>

		{% if error_message %}
			<p>
				<strong>{{ error_message }}</strong>
			</p>
		{% endif %}

		<form action="{% url 'polls:vote' question.id %}" method="post">
			{% csrf_token %}
			{% for choice in question.choice_set.all %}
				<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
				<label for="choice{{ forloop.counter }}">
					{{ choice.choice_text }}
				</label>
				<br />
			{% endfor %}

			<br />
			<label for="nom">
				Entrer votre nom
			</label>
			<input type="text" name="nom" id="nom" value="" />

			<input type="submit" value="Vote" />
		</form>
		
	</div>
</div>
{% endblock page %}

polls/templates/polls/index.html
{% extends "polls/layout.html" %}

{% block menuHome %}
	class="active"
{% endblock menuHome %}

{% block page %}
<div id="headerwrap">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2">
				<h1> Il faut faire attention à notre santé ! </h1>
				<h2> Aidez nous en répondant aux sondages, questionnaires. </h2>
			</div>
		</div>
	</div>
</div>


<div class="container">
	<div class="row">
		<div class="col-lg-6">		
			<div class="card">
				<div class="card-header">
					<h4 class="fa fa-check-circle-o">
						Derniers Sondages
					</h4>
				</div>
				<div class="card-body">
				{% if latest_sondage_list %}
					<ul>
					{% for question in latest_sondage_list %}
						<li>
							<a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
						</li>
					{% endfor %}
					</ul>
				{% else %}
					<p>Pas de sondages disponibles.</p>
				{% endif %}
				</div>
				<div class="card-footer">
					<a href="{% url 'polls:indexSondage' %}" class="btn btn-primary">
						Plus de sondages
					</a> 
				</div>
			</div>
		</div>


		<div class="col-lg-6">		
			<div class="card">
				<div class="card-header">
					<h4 class="fa fa-question-circle">
						Derniers Questionnaires
					</h4>
				</div>
				<div class="card-body">
					{% if latest_questionnaire_list %}
						<ul>
						{% for questionnaire in latest_questionnaire_list %}
							<li>
								<a href="{% url 'polls:detailQuestionnaire' questionnaire.id %}">{{ questionnaire.label }}</a>
							</li>
						{% endfor %}
						</ul>
					{% else %}
						<p>Pas de questionnaires disponibles.</p>
					{% endif %}
				</div>
				<div class="card-footer">
					<a href="{% url 'polls:indexQuestionnaire' %}" class="btn btn-primary">
						Plus de questionnaires
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock page %}

polls/templates/polls/layout.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="fr">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>
			{% block title %}
				Django application
			{% endblock title %}
		</title>

		<!-- Bootstrap -->
		<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">

		<!-- FICHIERS CSS -->
		{% load static %}
		{% block stylsheet %}
			<link rel="stylesheet" type="text/css" href="{% static 'polls/layout.css' %}" />
		{% endblock stylsheet %}
	</head>

	<body>

		<!-- MENU -->
		<div class="navbar navbar-inverse navbar-fixed-top">
		  	<div class="container">
		   		<div class="navbar-header">
		      		<button type="button" id="navigationToggle" class="navbar-toggle">
						<span class="icon-bar">.</span>
						<span class="icon-bar">.</span>
						<span class="icon-bar">.</span>
		     		</button>
		      		<div class="navbar-brand">P<span class="fa fa-circle">LLS</span></div>
		    	</div>
				<div class="navbar-collapse collapse">
				  	<ul class="nav navbar-nav navbar-right">
						<li {% block menuHome %} {% endblock menuHome %}>
							<a href="{% url 'polls:index' %}">
								Accueil
							</a>
						</li>
						<li {% block menuSondage %} {% endblock menuSondage %}>
							<a href="{% url 'polls:indexSondage' %}">
								<span class="fa fa-check-circle">
									Sondages
								</span>								
							</a>
						</li>
						<li {% block menuQuest %} {% endblock menuQuest %}>
							<a href="{% url 'polls:indexQuestionnaire' %}">
								<span class="fa fa-question-circle">
									Questionnaires
								</span>								
							</a>
						</li>
						<li {% block menuAdmin %} {% endblock menuAdmin %}>
							<a href="{% url 'admin:index' %}">
								<span class="fa fa-cog">
									admin
								</span>								
							</a>
						</li>	
				 	</ul>
				</div>
		  	</div>
		</div>

		{% block page %}		
		{% endblock page %}
		
		<!-- FOOTER -->
		<div id="footer">
			<div class="container">
				<div class="row">
					Création : Alice Bazanté	
				</div>
			</div>
		</div>
		
		<!-- JAVASCRIPT -->
		<script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"  type="text/javascript"></script>
		<script type="text/javascript">
			
			// Chargement du DOM fini
			$(function(){
				
				$('#navigationToggle').click(function(){
					$("div.navbar-collapse").toggle();		
				});
			
			});
		
		</script>
		{% block javascript %}
		{% endblock javascript %}
	
	</body>
</html>

polls/templates/polls/resultsQuestionnaire.html
{% extends "polls/layout.html" %}

{% block menuQuest %}
	class="active"
{% endblock menuQuest %}

{% block page %}
<div class="container">
	<div class="row">
	
		<div class="col-lg-12">
			<h1> {{ questionnaire.label }} </h1>
		</div>
		
	</div>
	
	<div class="row">
	
		<div class="col-lg-12">
			<h2>Récapitulatif des dernières réponses</h2>

			<div>
				{% if questionnaire.reponsequestionnaires_set.all|length >= 1 %}
					<ul>
					{% for reponseQuest in questionnaire.reponsequestionnaires_set.all|dictsortreversed:'id'|slice:":5" %}
						<li>
							{{ reponseQuest.nom|upper }}
							{% if reponseQuest.reponsequestionquestionnaire_set.all|length >= 1 %}
							<ul>
								{% for reponse in reponseQuest.reponsequestionquestionnaire_set.all %}
									<li>
										{{ reponse.question }} - {{ reponse.reponse }}
									</li>
								{% endfor %}
							</ul>
							{% endif %}
						</li>
						{% if  forloop.counter == 5 %}
							<li> ... </li>
						{% endif %}
					{% endfor %}
					</ul>
				{% endif %}
			</div>
		</div>		
		
		<div class="col-lg-12 actions">
			<a href="{% url 'polls:detailQuestionnaire' questionnaire.id %}" class="btn btn-primary">
				Répondre à nouveau
			</a>

			<a href="#" id="resultatPDF" class="btn btn-default">
				Liste des résultats en PDF
			</a>
		</div>

		<div class="col-lg-12 hide" id="graph">
			<h2> Boite à moustache des poids </h2>

			<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
		</div>

	</div>
</div>
{% endblock page %}


{% block javascript %}
<!-- highcharts (generation de graphique) -->
<script src="https://code.highcharts.com" type="text/javascript"></script>
<script src="https://code.highcharts.com/highcharts.js" type="text/javascript"></script>
<script src="https://code.highcharts.com/modules/data.js" type="text/javascript"></script>
<script src="https://code.highcharts.com/highcharts-more.js" type="text/javascript"></script>
<script src="https://code.highcharts.com/modules/exporting.js" type="text/javascript"></script>

<!-- pdfmake (generation de PDF) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.26/pdfmake.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.26/vfs_fonts.js" type="text/javascript"></script>

<script type="text/javascript">

	// Après le chargement du DOM
	$(function(){
				
		/************************/
		/* Gestion du graphique */
		/************************/
		
		var questions = [];
		var Allreponses = [];
		{% for question in questionnaire.questionquestionnaire_set.all %}
			var quest = "{{question.question}}";
			var position = quest.indexOf("poids");
			if (position != -1) {
				questions.push(quest);
			}
			Allreponses[quest] = [];
		{% endfor %}
		
		/* Si il y a une question parlant de poids, création du graphique */
		if (questions.length >= 1 ) {

			$('#graph').toggleClass("hide");

			{% for reponseQuest in questionnaire.reponsequestionnaires_set.all %}
				{% for reponse in reponseQuest.reponsequestionquestionnaire_set.all %}
					var rep = "{{reponse.reponse}}";
					if(isNaN(rep) == false && rep != "")
					{
						Allreponses["{{ reponse.question }}"].push(rep);
					}
				{% endfor %}
			{% endfor %}

			var reponses = [];
			var i = 0;
			while (i < questions.length) {
				reponses.push(Allreponses[questions[i]]);
				i++;
			}

			var mesData = [];
			for (var serie in reponses) {
				var nombres = reponses[serie].map(parseFloat);
				var serieTri = numSort(nombres);
				console.log(serieTri);
				var stat = [];
				stat.push(min(serieTri));
				stat.push(q1(serieTri));
				stat.push(mediane(serieTri));
				stat.push(q3(serieTri));
				stat.push(max(serieTri));
				mesData.push(stat);
			}

			Highcharts.chart('container', {
				chart: {
					type: 'boxplot'
				},
				title: {
					text: 'Résultat du questionnaire : '+'{{ questionnaire.label }}'
				},
				legend: {
					enabled: false
				},
				xAxis: {
					categories: questions,
					title: {
						text: 'questions'
					}
				},
				yAxis: {
					title: {
						text: 'Poids'
					}
				},
				series: [{
					name: 'Observations',
					data: mesData,
					tooltip: {
						headerFormat: 'Question {point.key} <br />'
					}
				}]
			});	
		}
		
		/******************/
		/* Gestion du PDF */
		/******************/
		
		var structureReponse = [];
		{% for reponseQuest in questionnaire.reponsequestionnaires_set.all|dictsort:'nom' %}
			structureReponse["{{ reponseQuest.nom }}"] = [];
			{% for reponse in reponseQuest.reponsequestionquestionnaire_set.all %}
				structureReponse["{{ reponseQuest.nom }}"].push("{{ reponse.question }} - {{ reponse.reponse }}");
			{% endfor %}
		{% endfor %}

		var entete = [];
		var body = [];
		for (var index in structureReponse) {
			body.push({ text: index, style: 'reponse'});
			body.push({ ul: structureReponse[index], style: 'list'});
			body.push({text: "\n"});		
		}

		var docDefinition = {
			footer: function(currentPage, pageCount) { 
				return { text: "Page "+currentPage.toString()+' / ' + pageCount , alignment: 'right', margin: [0,0,20,25] };
			},
			content: [
				{ 
					text: '{{ questionnaire.label }}', 
					style: 'header', 
					alignment: 'center' 
				},
				{text: "\n"},
				{
					text: 'Résultats triés par ordre alphabétique',
					style: 'titre'
				},
				{text: "\n"},
				body
			],
			styles: {
				header: {
					fontSize: 30,
					bold: true,
					alignment: 'justify'
				},
				reponse: {
					fontSize: 12,
					bold: true,
					margin: [5,5,5,5]
				},
				list: {
					fontSize: 12,
				},
				titre: {
					fontSize: 22,
					alignment: 'left'
				}
			}
		};

		$("#resultatPDF").click(function(){
			pdfMake.createPdf(docDefinition).download('questionnaire.pdf');
		});
		
		
		
	});
	
	/*************/
	/* Fonctions */
	/*************/

	function numSort(tab) { 
        var en_cours;     
        for (var i = 1; i < tab.length; i++) {
            en_cours = tab[i];
            for (var j = i; j > 0 && tab[j-1] > en_cours; j--) {
                tab[j] = tab[j-1];
            }
            tab[j] = en_cours;
        }
		return tab;
    }
	function min(serie) {
		return parseFloat(serie[0]);
	}
	function max(serie) {
		return parseFloat(serie[serie.length-1]);
	}
	function q1(serie) {
		var quartil = Math.ceil( (serie.length-1)/4 );
		return parseFloat(serie[quartil]);
	}
	function q3(serie) {
		var rang = Math.ceil( ((serie.length-1)/4)*3 );
		return parseFloat(serie[rang]);
	}
	function mediane(serie) {
		var milieu = Math.ceil( (serie.length-1)/2 );
		if ( (serie.length) % 2 == 1) {
            return parseFloat(serie[milieu]);
        } else {
            return ( (parseFloat(serie[milieu-1]) + parseFloat(serie[milieu]))/2.0);
        }
	}

</script>
{% endblock javascript %}

polls/templates/polls/resultsSondage.html
{% extends "polls/layout.html" %}

{% block menuSondage %}
	class="active"
{% endblock menuSondage %}

{% block page %}
<div class="container">
	<div class="row">
	
		<div class="col-lg-12">
			<h1> {{ question.question_text }} </h1>
		</div>
		
	</div>
	
	<div class="row">
	
		<div class="col-lg-6">
			<h2>Récapitulatif des votes par choix</h2>

			<div>
				{% if question.choice_set.all|length > 1 %}
				<ul>
					{% for choice in question.choice_set.all %}
						<li>
							<span class="choice">
								{{ choice.choice_text }} 
							</span>
							--
							<span class="resultat">
								{{ choice.votes }} 
							</span>
							vote{{ choice.votes|pluralize }}
						</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>

		<div class="col-lg-6">
			<h2>Détail des derniers votes</h2>

			<div>
				{% if question.reponse_set.all|length > 1 %}
				<ul>
				{% for reponse in question.reponse_set.all|dictsortreversed:'id'|slice:":5" %}
					<li>
						{{ reponse.nom|upper }} -- {{ reponse.choice.choice_text }}
					</li>
					{% if  forloop.counter == 5 %}
						<li> ... </li>
					{% endif %}
				{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>		
		
		<div class="col-lg-12" id="mesactions">
			<div class="row">
				<div class="col-lg-6">
					<a href="{% url 'polls:detail' question.id %}" class="btn btn-primary">
						Voter à nouveau
					</a>
				</div>
				<div class="col-lg-6">
					<a href="#" id="resultatPDF" class="btn btn-default">
						Liste des résultats en PDF
					</a>				
				</div>
			</div>
		</div>

		<div class="col-lg-12">
			<h2> Fréquence des votes </h2>

			<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
		</div>

	</div>
</div>
{% endblock page %}


{% block javascript %}
<!-- highcharts (generation de graphique) -->
<script src="https://code.highcharts.com" type="text/javascript"></script>
<script src="https://code.highcharts.com/highcharts.js" type="text/javascript"></script>
<script src="https://code.highcharts.com/modules/data.js" type="text/javascript"></script>
<script src="https://code.highcharts.com/modules/exporting.js" type="text/javascript"></script>

<!-- pdfmake (generation de PDF) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.26/pdfmake.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.26/vfs_fonts.js" type="text/javascript"></script>

<script type="text/javascript">

	// Après le chargement du DOM
	$(function(){
	
		/***************************/
		/* Génération du graphique */
		/***************************/
	
		var labels = ['null'];
		$('span.choice').each(function(){
			labels.push($(this).text());
		});
		var resultats = [];
		var question = $('h1').text();
		resultats.push('choix');
		var nbRes= 0;
		$('span.resultat').each(function(){
			nbRes += parseInt($(this).text());
		});
		$('span.resultat').each(function(){
			resultats.push( (parseInt($(this).text())*100)/nbRes );
		});
		
		Highcharts.chart('container', {
			data: {
				rows: [
				    labels,
				    resultats
				]
			},
			chart: {
				type: 'column'
			},
			title: {
				text: 'Résultat du sondage : '+question
			},
			yAxis: {
				title: {
				    text: 'frequence'
				},
				min: 0,
				max: 100
			},
			tooltip: {
				formatter: function () {
				    return "<b>"+this.series.name+"<\/b> <br/>" +
				        this.point.y + '% ' + this.point.name.toLowerCase();
				}
			}
		});
	
		/*********************/
		/* Génération du PDF */
		/*********************/

		var structureReponse = [];
		{% for choice in question.choice_set.all %}
			structureReponse["{{ choice.choice_text}}"] = [];
		{% endfor %}
		{% for reponse in question.reponse_set.all|dictsort:'nom' %}
			structureReponse["{{ reponse.choice.choice_text }}"].push("{{ reponse.nom|upper }}");
		{% endfor %}

		var entete = [];
		var body = [];
		for (var index in structureReponse) {
			entete.push({ text: index, style: 'reponse'});
			body.push({ ul: structureReponse[index]});			
		}

		var docDefinition = {
			footer: function(currentPage, pageCount) { 
				return { text: "Page "+currentPage.toString()+' / ' + pageCount , alignment: 'right', margin: [0,0,20,25] };
			},
			content: [
				{ 
					text: '{{ question.question_text }}', 
					style: 'header', 
					alignment: 'center' 
				},
				{
					text: "\n"
				},
				{
					text: 'Listes des résultats triés par ordre alphabétique',
					style: 'titre'
				},
				{
					text: "\n"
				},
				{
					columns: entete
				},
				{
					columns: body
				},
			],
			styles: {
				header: {
					fontSize: 30,
					bold: true,
					alignment: 'justify'
				},
				reponse: {
					fontSize: 16,
					bold: true,
					margin: [5,5,5,5]
				},
				titre: {
					fontSize: 22,
					alignment: 'left'
				}
			}
		};

		$("#resultatPDF").click(function(){
			pdfMake.createPdf(docDefinition).download('sondage.pdf');
		});
				
	});

</script>
{% endblock javascript %}